# Generated by Django 2.0.13 on 2019-07-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='session',
        ),
    ]
