# Generated by Django 2.0.13 on 2019-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190713_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session1_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('imageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session1_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('imageUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session1_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('imageUrl', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Session1_1',
        ),
    ]
