# Generated by Django 2.0.13 on 2019-07-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session1_1',
            new_name='Area1',
        ),
    ]
