# Generated by Django 2.0.13 on 2019-07-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20190720_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
